/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminChat: typeof import('./components/AdminChat.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AudioStream: typeof import('./components/AudioStream.vue')['default']
    BackOffice: typeof import('./components/BackOffice.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Landing: typeof import('./components/Landing.vue')['default']
    PrivacyPolicy: typeof import('./components/PrivacyPolicy.vue')['default']
    RadioChat: typeof import('./components/RadioChat.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UpcomingEvents: typeof import('./components/UpcomingEvents.vue')['default']
    UpcommingEvents: typeof import('./components/UpcommingEvents.vue')['default']
    VideoStream: typeof import('./components/VideoStream.vue')['default']
  }
}
